### ISSUE TITLE
Create release for CFP Hackathon build

### ISSUE THREAD

**Issue by ShabazBadshah** [grey-software/open-gov#21]
When the CFP competition has concluded, and the winners have been announced, we should create a release for the 1.0 version so the codebase history is easy to follow

**Comment by ArsalaBangash** [comment]
@ShabazBadshah I'm not sure if we want to create an official release for something that may not be ready for release by the end of the hackathon.

**Comment by ShabazBadshah** [comment]
@ArsalaBangash  my definition of a release is whenever we make a variation of a product publicly available (either MVP or prod), which in this case, our CFP submission was. We can wait till the end of the hackathon and decide whether we need one or not.
